name : 'my first container action'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    defaut: 'Rafik TAAMMA'
  
  outputs:
    myOutput:
      description: 'total memory'
  
  runs:
    using: 'docker'
    image: 'Dockerfile'
    

