on: [push]

jobs:
  my_job:
    runs-on : ubuntu-latest


    steps:
      - uses : actions/checkout@v2
      - name : run the action
        id : hello
        uses: ./
        with:
          myInput: ' Rafik Baghdad TAAMMA'
      
      - name : print the output
        run : |
          echo ${{ steps.hello.outputs.memory }}
          echo "total memory successfully output"
        